name: Generate Everything

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-pdf:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check words for proper syllabary
        run: |
          python check-words.py strict

      - name: Generate dictionary files
        run: |
          python generate-tex-dictionary.py
          python generate-tex-dictionary.py en

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex          
          working_directory: small-andro-polish-dictionary

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex          
          working_directory: small-andro-english-dictionary

      - uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex          
          working_directory: the-book

      - name: Generate final PDFs
        run: |
          cd $GITHUB_WORKSPACE/small-andro-polish-dictionary/          
          cp main.pdf ../final/small-andro-polish-dictionary.pdf

          cd $GITHUB_WORKSPACE/small-andro-english-dictionary/
          cp main.pdf ../final/small-andro-english-dictionary.pdf

          cd $GITHUB_WORKSPACE/the-book/
          cp main.pdf ../final/andro-language-reference-guide.pdf

      - name: Generate MD tables and wordlists
        run: |
          cd $GITHUB_WORKSPACE/
          python generate-md.py
          python generate-md.py en
          python generate-wordlist.py

      - name: Generate HTML page
        run: |
          cd $GITHUB_WORKSPACE/
          python generate-html-dictionary.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifact
          path: final/

