name: Generate Everything

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:  
  build-pdf:
    runs-on: ubuntu-latest
    
    steps:    
    - uses: actions/checkout@v2
      
    - name: Setup Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    
    - name: Install XeLaTeX tooling
      run: |
        sudo apt-get update
        sudo apt-get install texlive-xetex texlive-lang-polish texlive-fonts-extra -y
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install unidecode
    
    - name: Check words for proper syllabary
      run: |
        cd $GITHUB_WORKSPACE/scripts
        python check-words.py strict

    - name: Generate dictionary files
      run: |
        cd $GITHUB_WORKSPACE/scripts
        python generate-tex-dictionary.py

    - name: Generate final PDF
      run: | 
        xelatex main.tex
        
        # second time to resolve some reference problems
        xelatex main.tex
        
        mkdir final
        cp main.pdf final/small-andro-polish-dictionary.pdf

    - name: Generate MD tables
      run: | 
        cd $GITHUB_WORKSPACE/scripts
        python generate-md.py
                
        cp tables.md ../final/
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:        
        name: artifact
        path: final/